apiVersion: v1
kind: Pod
metadata:
  name: grid-sync
  labels:
    tier: api
spec:
  volumes:
    - name: rg
      persistentVolumeClaim:
        claimName: rg
  containers:
  - name: schema
    imagePullPolicy: Always
    image: argovis/grid-sync:dev
    #command: ['sleep', '1000000']
    command: ['bash', 'append_rg_month.sh', '2024', '10']
    volumeMounts:
      - mountPath: "/tmp/rg"
        name: rg
    resources:
      requests:
        memory: "0Gi"
        cpu: "0m"
      limits:
        memory: 1000Mi
        cpu: 1000m
  restartPolicy: Never
